package com.doughepi.main;

import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;

/**
 * @author Piper Dougherty
 * @version 1.0
 * <p>
 * Manages the movement between the login view and the main view.
 */
public class Manager
{
	private Stage stage;

	/**
	 * @param stage The scene created on start used in all JavaFX applications.
	 */
	public Manager(Stage stage)
	{
		this.stage = stage;
	}

	/**
	 * When called invokes a change to the main view.
	 *
	 * @param sessionID The session id generated by the login controller.
	 */
	public void doLogin(String sessionID)
	{
		setScene_Main(sessionID);
	}

	/**
	 * When called invokes a change to the login view.
	 */
	public void doLogout()
	{
		setScene_Login();
	}

	/**
	 * Handles the change to the login view.
	 */
	public void setScene_Login()
	{
		URL url = getClass().getResource("login.fxml");
		FXMLLoader fxmlLoader = new FXMLLoader(url);

		try
		{
			Parent root = fxmlLoader.load();
			stage.setScene(new Scene(root, 231, 115));
			LoginController loginController = fxmlLoader.<LoginController>getController();
			loginController.initializeManager(this);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}

	/**
	 * Handles the change to the main view.
	 *
	 * @param sessionID The session id generated by the login controller.
	 */
	public void setScene_Main(String sessionID)
	{
		URL url = getClass().getResource("main.fxml");
		FXMLLoader fxmlLoader = new FXMLLoader(url);

		try
		{
			Parent root = fxmlLoader.load();
			stage.setScene(new Scene(root, 600, 400));
			MainController mainController = fxmlLoader.<MainController>getController();
			mainController.initializeSessionID(this, sessionID);
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
	}

	public void setScene_Register()
	{
		URL url = getClass().getResource("register.fxml");
		FXMLLoader fxmlLoader = new FXMLLoader(url);

		Parent root = null;
		try
		{
			root = fxmlLoader.load();
		}
		catch (IOException e)
		{
			e.printStackTrace();
		}
		stage.setScene(new Scene(root, 326, 190));
		RegisterController registerController = fxmlLoader.<RegisterController>getController();
		registerController.initializeManager(this);
	}
}
